name: Electron App Build and Update

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install Dependencies
        run: npm install
      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic
          sudo snapcraft --version  # 验证安装

      - name: Build Electron App
        run: npm run build
        env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
           dist/*.exe
           dist/*.exe.blockmap
           dist/latest.yml
           draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx electron-builder --win --x64 --publish always
